spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:data.sql
