/*
 * This file is generated by jOOQ.
 */
package com.larscheng.www.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1192891673;

    private Integer       id;
    private String        name;
    private Integer       age;
    private LocalDateTime createDate;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.createDate = value.createDate;
    }

    public User(
        Integer       id,
        String        name,
        Integer       age,
        LocalDateTime createDate
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
