/*
 * This file is generated by jOOQ.
 */
package com.larscheng.www.jooq.tables.records;


import com.larscheng.www.jooq.tables.Celebrity;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CelebrityRecord extends UpdatableRecordImpl<CelebrityRecord> implements Record5<Integer, String, String, LocalDate, String> {

    private static final long serialVersionUID = -1407582738;

    /**
     * Setter for <code>students.celebrity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>students.celebrity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>students.celebrity.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>students.celebrity.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>students.celebrity.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>students.celebrity.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>students.celebrity.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>students.celebrity.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>students.celebrity.birth_place</code>.
     */
    public void setBirthPlace(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>students.celebrity.birth_place</code>.
     */
    public String getBirthPlace() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDate, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDate, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Celebrity.CELEBRITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Celebrity.CELEBRITY.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Celebrity.CELEBRITY.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Celebrity.CELEBRITY.DATE_OF_BIRTH;
    }

    @Override
    public Field<String> field5() {
        return Celebrity.CELEBRITY.BIRTH_PLACE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public LocalDate component4() {
        return getDateOfBirth();
    }

    @Override
    public String component5() {
        return getBirthPlace();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public LocalDate value4() {
        return getDateOfBirth();
    }

    @Override
    public String value5() {
        return getBirthPlace();
    }

    @Override
    public CelebrityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CelebrityRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CelebrityRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CelebrityRecord value4(LocalDate value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public CelebrityRecord value5(String value) {
        setBirthPlace(value);
        return this;
    }

    @Override
    public CelebrityRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CelebrityRecord
     */
    public CelebrityRecord() {
        super(Celebrity.CELEBRITY);
    }

    /**
     * Create a detached, initialised CelebrityRecord
     */
    public CelebrityRecord(Integer id, String firstName, String lastName, LocalDate dateOfBirth, String birthPlace) {
        super(Celebrity.CELEBRITY);

        set(0, id);
        set(1, firstName);
        set(2, lastName);
        set(3, dateOfBirth);
        set(4, birthPlace);
    }
}
