/*
 * This file is generated by jOOQ.
 */
package com.larscheng.www.jooq;


import com.larscheng.www.jooq.tables.Celebrity;
import com.larscheng.www.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students extends SchemaImpl {

    private static final long serialVersionUID = -1859109684;

    /**
     * The reference instance of <code>students</code>
     */
    public static final Students STUDENTS = new Students();

    /**
     * The table <code>students.celebrity</code>.
     */
    public final Celebrity CELEBRITY = com.larscheng.www.jooq.tables.Celebrity.CELEBRITY;

    /**
     * The table <code>students.user</code>.
     */
    public final User USER = com.larscheng.www.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Students() {
        super("students", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Celebrity.CELEBRITY,
            User.USER);
    }
}
