/*
 * This file is generated by jOOQ.
 */
package com.larscheng.www.jooq;


import com.larscheng.www.jooq.tables.Celebrity;
import com.larscheng.www.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in students
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>students.celebrity</code>.
     */
    public static final Celebrity CELEBRITY = Celebrity.CELEBRITY;

    /**
     * The table <code>students.user</code>.
     */
    public static final User USER = User.USER;
}
